### ISSUE TITLE
call done() before add()

### ISSUE THREAD

**Issue by Sheraff** [chemzqm/parallel#1]
I like this small package. Very handy and without all the clutter. 
Would it be possible to allow for calling done() before any add()?

**Comment by chemzqm** [comment]
The problem is the behaviour would be confusing, what should we do with the callback added after done is called or there is a timeout error thrown, if you need a timeout, just add it inside the callback function:

``` js
parallel.add(function(done) {
  setTimeout(function() {
    request.get("/", done);
  }, 200);
});
```
